name: Hello World Workflow

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'List of image tags'
        required: true
        default: '["alpine", "python"]'

jobs:
  say-hello:
    runs-on: ubuntu-latest  

    steps:
    - name: Print a greeting
      run: echo "Hello, world!"
