name: Hello World Workflow

on:
  schedule:
    - cron: '*/5 * * * *'  
  # workflow_dispatch:
  #   inputs:
  #     image:
  #       description: 'List of image tags'
  #       required: true
  #       default: '["alpine", "python"]'

jobs:
  say-hello:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print a greeting
      run: echo "Hello, world!"

    - name: Print the image tags
      run: |
        echo "Image tags received"
